Repository adarsh-singh01/PrithWe, pull requests merged in 2024-07, with the labels that each got.

#166 Feat: Home page animation added
  client/package.json
  client/src/components/Accordian/Accordian.jsx
  client/src/components/BelowHero.jsx
  client/src/components/Header.jsx
  client/src/components/Hero.jsx
  client/src/components/InfoCard.jsx
Labels: enhancement, level2, gssoc

#188 Added OAuth guide
  README.md
Labels: documentation, level1, gssoc

#186 Google o auth
  client/src/assets/OAuthLogo.png
  client/src/assets/google.png
  client/src/components/Header.jsx
  client/src/components/LoginForm.jsx
  client/src/components/RegisterForm.jsx
  package-lock.json
  package.json
  server/Authentication.js
  server/dbCommands.sql
  server/index.js
Labels: enhancement, level3, gssoc
