Repository adarsh-singh01/PrithWe, pull requests merged in 2024-06, with the labels that each got.

#37 Fixed the force reload issue and improved the toastify notification
  client/src/App.jsx
  client/src/components/BusinessForm.jsx
  client/src/components/Header.jsx
  client/src/components/HouseholdForm.jsx
  client/src/components/LoginForm.jsx
  client/src/components/RegisterForm.jsx
  client/src/pages/Login.jsx
Labels: enhancement, level2, gssoc

#17 [Fixes]: Invalid Input Sanitization #8
  client/src/components/BusinessForm.jsx
  client/src/components/HouseholdForm.jsx
  package-lock.json
  package.json
Labels: level2, gssoc

#32 Toggle password
  client/package-lock.json
  client/package.json
  client/src/components/Header.jsx
  client/src/components/LoginForm.jsx
  client/src/components/RegisterForm.jsx
Labels: enhancement, level2, gssoc

#56 User Verification added
  client/src/App.jsx
  client/src/components/LoginForm.jsx
  client/src/components/RegisterForm.jsx
  client/src/pages/VerifyEmail.jsx
  package-lock.json
  package.json
  server/Authentication.js
  server/SendOTP.js
  server/dbCommands.sql
Labels: enhancement, level3, gssoc

#49 add dark/light mode toggle btn
  client/index.html
  client/public/moon.png
  client/public/sun.png
  client/src/App.css
  client/src/App.jsx
  client/src/assets/Archesblack.png
  client/src/assets/moon.png
  client/src/assets/sun.png
  client/src/components/BelowHero.jsx
  client/src/components/Header.jsx
  client/src/components/Hero.jsx
  client/src/components/InfoCard.jsx
  client/src/components/LoginForm.jsx
  client/src/components/RegisterForm.jsx
  client/src/pages/AboutUs.jsx
  client/src/pages/Information.jsx
Labels: enhancement, level2, gssoc

#59 Added Forgot Password Feature
  client/src/App.jsx
  client/src/components/LoginForm.jsx
  client/src/pages/ResetPassword.jsx
  client/src/pages/VerifyEmail.jsx
  package-lock.json
  server/Authentication.js
  server/SendOTP.js
  server/db.js
Labels: enhancement, level3, gssoc

#64 admin Dashboard added
  README.md
  client/src/App.jsx
  client/src/Layout.jsx
  client/src/components/AdminDashBoardComp.jsx
  client/src/components/ContactDetails.jsx
  client/src/components/Header.jsx
  client/src/components/LoginForm.jsx
  client/src/components/UserList.jsx
  client/src/pages/AdminDashboard.jsx
  server/Authentication.js
  server/adminData.js
  server/index.js
Labels: enhancement, level3, gssoc

#71 Handle menu toggle collapse menu when user click on it
  client/src/components/Header.jsx
Labels: enhancement, level1, gssoc

#57 updated auto scroll to top
  client/src/App.jsx
  client/src/components/ScrollToTop.jsx
Labels: enhancement, level1, gssoc

#81 Added Tips section
  client/src/App.jsx
  client/src/components/Header.jsx
  client/src/components/TipsSection.jsx
  client/src/pages/Tips.jsx
Labels: enhancement, level2, gssoc

#86 "AddedProfessinalEmailSender"
  server/EmailTemplate/emailTemplate.html
  server/SendOTP.js
Labels: enhancement, level2, gssoc

#88 Added User Details in admin Section
  client/src/App.jsx
  client/src/Layout.jsx
  client/src/components/UserDetailsSection.jsx
  client/src/components/UserList.jsx
  client/src/pages/UserDetails.jsx
  package-lock.json
  package.json
  server/adminData.js
  server/businessData.js
Labels: enhancement, level3, gssoc

#85 FEAT: - History page
  client/src/App.jsx
  client/src/components/BusinessForm.jsx
  client/src/components/CarbonCalculator.jsx
  client/src/components/Header.jsx
  client/src/components/HistoryCompoForBusi.jsx
  client/src/components/HistoryCompoForHouse.jsx
  client/src/components/HistoryForBusiness.jsx
  client/src/components/HistoryForHousehold.jsx
  client/src/components/HouseholdForm.jsx
  client/src/pages/History.jsx
  server/businessData.js
  server/householdData.js
Labels: enhancement, level3, gssoc

#97 Added AI integration for recommendation
  client/src/components/BusinessForm.jsx
  client/src/components/HouseholdForm.jsx
  client/src/components/HouseholdResult.jsx
  package-lock.json
  package.json
  server/businessData.js
  server/dbCommands.sql
  server/householdData.js
Labels: enhancement, level3, gssoc

#95 Resolves Bug No.#89 & Major UI Changes on VerifyEmail & ResetPassword Pages
  client/src/pages/ResetPassword.jsx
  client/src/pages/VerifyEmail.jsx
  package-lock.json
  package.json
Labels: enhancement, level2, gssoc

#101 "Added Two Way Communication"
  client/src/components/ContactUsForm.jsx
  client/src/pages/ResetPassword.jsx
  client/src/pages/VerifyEmail.jsx
  server/EmailTemplates/FormData.html
  server/EmailTemplates/SendOtp.html
  server/EmailTemplates/ThankYou.html
  server/SendContactEmail.js
  server/SendOTP.js
  server/contactUs.js
  server/dbCommands.sql
Labels: enhancement, level3, gssoc

#112 404 error page
  client/src/App.jsx
  client/src/assets/error.png
  client/src/components/AdminSideChart.jsx
  client/src/components/HouseholdForm.jsx
  client/src/components/UserDetailsSection.jsx
  client/src/pages/Error.jsx
  package-lock.json
  server/householdData.js
Labels: enhancement, level2, gssoc

#120 fixing issue no #76
  client/src/components/Header.jsx
Labels: enhancement, level2, gssoc

#114 Create LICENSE
  LICENSE
Labels: documentation, level1, gssoc

#121 Fix in UI of User Details (Admin Panel)
  client/src/components/UserDetailsSection.jsx
Labels: enhancement, level3, gssoc

#127 "AddedDetailsforlocalSetup"
  README.md
  images/AppPassword1.png
  images/AppPassword2.png
  images/QueryTools.png
  images/database.png
Labels: documentation, level2, gssoc

#143 Fix business data UI and other bug (Admin Panel)
  client/src/components/AdminSideChart.jsx
  client/src/components/UserDetailsSection.jsx
  client/src/pages/UserDetails.jsx
Labels: enhancement, level3, gssoc

#146 Updated History page UI
  client/src/components/HistoryCompoForBusi.jsx
  client/src/components/HistoryForBusiness.jsx
  client/src/components/HistoryForHousehold.jsx
Labels: enhancement, level3, gssoc
